runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: culture.app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^Makefile$
- ^alertlib-src/.*$
